name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04

    steps:
    - run: apt-get update -y
    - run: apt-get install -y libgtk-3-dev libglib2.0-dev libgraphene-1.0-dev libcairo-gobject2 libcairo2-dev
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      working-directory: envoyer
      run: cargo build --verbose
    - name: Run tests
      working-directory: envoyer
      run: cargo test --verbose
